"""Regenerate copied inventory facts; never manufacture a reviewed classification.

Run with --write after adding storage names, timer sites or real_browser tests.
New timer/storage entries receive UNCLASSIFIED, which the existing guards reject.
Review and fill that field; generation is not authority or quota review.
Without --write, fail on drift. Background plugin callsites are generated by
check_background_authority_inventory directly from canonical CLASSIFICATION.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def insert_entries(source: str, name: str, entries: list[str]) -> str:
    """Preserve reviewed values and comments; append only discovered facts."""
    if not entries:
        return source
    tree = ast.parse(source)
    node = next(
        n for n in tree.body
        if isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name)
        and n.target.id == name
    )
    lines = source.splitlines(keepends=True)
    lines.insert(node.end_lineno - 1, "".join(f"    {entry},\n" for entry in entries))
    return "".join(lines)


def browser_workflow(source: str, marked_files: set[str]) -> str:
    """Only the proof-file block is generated; reviewed product paths stay put."""
    start = source.index("      # The proofs.")
    end = source.index("  workflow_dispatch:", start)
    files = marked_files | {"tests/test_ui_preview.py"}
    block = "      # The proofs. Generated by scripts/generate_guard_inventories.py.\n"
    block += "".join(f'      - "{path}"\n' for path in sorted(files))
    return source[:start] + block + source[end:]


def generate(root: Path) -> dict[Path, str]:
    from scripts.ci_assert_junit_case import marked_cases
    from tests import control_plane_timer_inventory as timers
    from tests.test_control_plane_inventory import _scan
    from tests.test_storage_registry_complete import _names_in_source
    from tinyassets import storage_accounting as storage

    timer_path = root / "tests/control_plane_timer_inventory.py"
    storage_path = root / "tinyassets/storage_accounting.py"
    workflow_path = root / ".github/workflows/real-browser-proof.yml"
    classified = set(storage.ROOT_ENTRIES) | storage.UNIVERSE_ENTRIES | storage.ELSEWHERE_ENTRIES
    return {
        timer_path: insert_entries(
            timer_path.read_text(encoding="utf-8"), "CLASSIFICATION",
            [f'{site!r}: ("UNCLASSIFIED", "review required")'
             for site in sorted(_scan() - timers.CLASSIFICATION.keys())],
        ),
        storage_path: insert_entries(
            storage_path.read_text(encoding="utf-8"), "ROOT_ENTRIES",
            [f'{name!r}: "UNCLASSIFIED: review required"'
             for name in sorted(_names_in_source().keys() - classified)],
        ),
        workflow_path: browser_workflow(
            workflow_path.read_text(encoding="utf-8"),
            {case.split("::")[0] for case in marked_cases(root, "real_browser")},
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    changed = []
    for path, content in generate(ROOT).items():
        if path.read_text(encoding="utf-8") != content:
            changed.append(path.relative_to(ROOT).as_posix())
            if args.write:
                path.write_text(content, encoding="utf-8")
    if changed:
        print("Inventory facts changed: " + ", ".join(changed))
        print("Run --write, then review every UNCLASSIFIED field; guards remain required.")
    return int(bool(changed) and not args.write)


if __name__ == "__main__":
    raise SystemExit(main())
