#!/usr/bin/env python3
"""Export the TinyAssets mark to every surface that carries it.

The drawings live in ``tinyassets/desktop/icon_gen.py`` (one geographic source
and palette, with full/compact/micro optical variants). This script renders
them out (dev machine only; needs Pillow) so the
site, the repo brand assets, the served web app, the desktop and Android apps,
the tray and the Play listing all show the same symbol.

Run from the repo root::

    python WebSite/brand/render_marks.py

Outputs (all overwritten):

- ``WebSite/brand/mark.svg`` (full seal), ``mark-compact.svg`` (compact disc),
  and ``mark-tile.svg`` (compact tile)
- ``WebSite/site-react/public/``: favicon.ico, icon.svg, apple-touch-icon.png,
  icon-192.png, icon-512.png, logo-mark.png, tinyassets-mark.png
- ``assets/icon.png``, ``assets/icon.svg``, ``assets/brand/tinyassets-logo-{icon,mark}.{png,svg}``
- ``assets/brand/tinyassets-app.{ico,icns}`` (Electron package icons)
- ``tinyassets/desktop/app.ico`` (Windows tray; also used by the launcher)
- ``mobile/resources/{icon,splash}.png`` + the Android density set +
  ``docs/ops/play-assets/{icon-512,feature-graphic-1024x500}.png`` via
  ``mobile/scripts/render_app_icons.py --from-logo``

The OG card (``og-image.png``) is rendered separately by ``render_og.py``
because it needs the site's web fonts.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from scripts.invariants.brand_parity import app_badge_data_uri  # noqa: E402
from tinyassets.desktop import icon_gen  # noqa: E402
from tinyassets.desktop.icon_gen import draw_mark, generate_icon, mark_svg  # noqa: E402

BRAND = REPO / "WebSite" / "brand"
SITE_PUBLIC = REPO / "WebSite" / "site-react" / "public"
SITE_COMPONENT = REPO / "WebSite" / "site-react" / "components" / "TinyAssetsMark.tsx"
ASSETS = REPO / "assets"
TRAY_ICO = REPO / "tinyassets" / "desktop" / "app.ico"
APP_HTML = REPO / "tinyassets" / "onboarding" / "app.html"
PROVENANCE = BRAND / "generated-assets.json"

# The generated component is TSX, so its lines follow JSX conventions, not ruff's.
# ruff: noqa: E501

_JSX_ATTRS = {
    "clip-path": "clipPath",
    "stroke-width": "strokeWidth",
    "stroke-linecap": "strokeLinecap",
    "stroke-linejoin": "strokeLinejoin",
    "fill-rule": "fillRule",
    "aria-label": "aria-label",
}


def _to_jsx(svg: str, id_expr: str) -> str:
    """The emblem SVG as JSX: camel-case attributes and a per-instance clip id."""
    body = svg.strip()
    body = body[body.index(">") + 1 : body.rindex("</svg>")]
    for kebab, camel in _JSX_ATTRS.items():
        body = body.replace(f"{kebab}=", f"{camel}=")
    body = body.replace('"ta-badge"', "{" + id_expr + "}")
    body = body.replace('"url(#ta-badge)"', "{`url(#${" + id_expr + "})`}")
    body = body.replace("/>", " />")
    return body


COMPONENT_TEMPLATE = '''// GENERATED by WebSite/brand/render_marks.py from tinyassets/desktop/icon_gen.py.
// Do not hand-edit: change the EMBLEM layer list there and re-run the exporter,
// so the inline mark can never drift from the icons, the tray, or the stores.
import * as React from "react";

// Content fingerprint used by every browser-loaded mark URL. A new drawing gets
// a new URL even when a browser has cached the old favicon indefinitely.
export const TINYASSETS_MARK_VERSION = "{mark_version}";

/**
 * The compact TinyAssets mark: Mount Baker from Everett, a howling wolf, the
 * ember moon, and the galaxy. `tile` squares the badge off for an app icon.
 */
export function TinyAssetsMark({{
  size = 28,
  tile = false,
  title,
}}: {{
  size?: number;
  /** Square the badge off with rounded corners (app icons, dense rows). */
  tile?: boolean;
  /** Accessible name; omit for a decorative mark beside the wordmark. */
  title?: string;
}}) {{
  const clipId = `ta-badge-${{React.useId().replace(/:/g, "")}}`;
  return (
    <svg
      className="tinyassets-mark"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 {viewbox:g} {viewbox:g}"
      width={{size}}
      height={{size}}
      role={{title ? "img" : undefined}}
      aria-hidden={{title ? undefined : true}}
      aria-label={{title}}
      style={{{{ display: "block", flexShrink: 0 }}}}
    >
      {{tile ? (
        <>{tile_body}</>
      ) : (
        <>{disc_body}</>
      )}}
    </svg>
  );
}}

export default TinyAssetsMark;
'''


def _write_component(mark_version: str) -> None:
    g = icon_gen
    SITE_COMPONENT.write_text(
        COMPONENT_TEMPLATE.format(
            mark_version=mark_version,
            viewbox=g.VIEWBOX,
            disc_body=_to_jsx(g.mark_svg(tile=False, detail="compact"), "clipId"),
            tile_body=_to_jsx(g.mark_svg(tile=True, detail="compact"), "clipId"),
        ),
        encoding="utf-8",
        newline="\n",
    )
    print(SITE_COMPONENT.relative_to(REPO).as_posix())


def _write_site_manifest(mark_version: str) -> None:
    """Generate the PWA manifest with the same content fingerprint as the page."""
    manifest = {
        "name": "TinyAssets",
        "short_name": "TinyAssets",
        "description": (
            "Your own AI command center. Runs on the subscription you already pay for."
        ),
        "start_url": "/",
        "display": "browser",
        "background_color": "#14140f",
        "theme_color": "#14140f",
        "icons": [
            {
                "src": f"/icon-192.png?v={mark_version}",
                "sizes": "192x192",
                "type": "image/png",
            },
            {
                "src": f"/icon-512.png?v={mark_version}",
                "sizes": "512x512",
                "type": "image/png",
            },
            {
                "src": f"/icon.svg?v={mark_version}",
                "sizes": "any",
                "type": "image/svg+xml",
            },
        ],
    }
    _write(
        SITE_PUBLIC / "site.webmanifest",
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
    )


def _write_app_html(tile_svg: str) -> None:
    """Point the served web app's favicon and brand glyph at the same badge.

    This was hand-patched once and then went stale the moment the mark changed:
    the app was still showing a retired monogram while every other surface had
    moved on (Codex review, 2026-09-02). Generating it closes that gap.

    Only the badge is owned here, so app.html is NOT in the receipt: brand
    parity checks the badge against mark-tile.svg instead of hashing a file
    every feature edits.
    """
    import re

    data_uri = app_badge_data_uri(tile_svg)
    html = APP_HTML.read_text(encoding="utf-8")
    before = html
    html = re.sub(r'<link rel="icon" href="data:image/svg\+xml,[^"]*" />',
                  f'<link rel="icon" href="{data_uri}" />', html, count=1)
    html = re.sub(r'--brand-mark:url\("data:image/svg\+xml,[^"]*"\);',
                  f'--brand-mark:url("{data_uri}");', html, count=1)
    if data_uri not in html:
        raise SystemExit(
            "render_marks: could not place the badge in app.html -- its favicon "
            "link or --brand-mark variable no longer matches the expected shape"
        )
    if html != before:
        APP_HTML.write_text(html, encoding="utf-8", newline="\n")
    print(APP_HTML.relative_to(REPO).as_posix())


def _write(path: Path, data: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(data, str):
        path.write_text(data, encoding="utf-8", newline="\n")
    else:
        path.write_bytes(data)
    print(path.relative_to(REPO).as_posix())


def _png(path: Path, size: int, tile: bool, detail: str | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    draw_mark(size, tile=tile, detail=detail).save(path, optimize=True)
    print(f"{path.relative_to(REPO).as_posix()} {size}x{size}")


def _ico(path: Path, sizes: tuple[int, ...]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    images = [draw_mark(s, tile=True, detail="micro" if s <= 32 else "compact")
              for s in sizes]
    images[-1].save(
        path, format="ICO", sizes=[(s, s) for s in sizes], append_images=images[:-1]
    )
    print(f"{path.relative_to(REPO).as_posix()} {sizes}")


def _icns(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    sizes = (16, 32, 64, 128, 256, 512, 1024)
    images = [
        draw_mark(s, tile=True, detail="micro" if s <= 32 else "compact")
        for s in sizes
    ]
    images[-1].save(path, format="ICNS", append_images=images[:-1])
    print(f"{path.relative_to(REPO).as_posix()} {sizes}")


def _generated_paths() -> list[Path]:
    """Every committed artifact whose bytes are owned by this exporter."""
    fixed = [
        BRAND / "mark.svg",
        BRAND / "mark-compact.svg",
        BRAND / "mark-tile.svg",
        SITE_COMPONENT,
        SITE_PUBLIC / "favicon.ico",
        SITE_PUBLIC / "icon.svg",
        SITE_PUBLIC / "apple-touch-icon.png",
        SITE_PUBLIC / "icon-192.png",
        SITE_PUBLIC / "icon-512.png",
        SITE_PUBLIC / "logo-mark.png",
        SITE_PUBLIC / "tinyassets-mark.png",
        SITE_PUBLIC / "site.webmanifest",
        ASSETS / "icon.png",
        ASSETS / "icon.svg",
        ASSETS / "brand" / "tinyassets-logo-icon.png",
        ASSETS / "brand" / "tinyassets-logo-icon.svg",
        ASSETS / "brand" / "tinyassets-logo-mark.png",
        ASSETS / "brand" / "tinyassets-logo-mark.svg",
        ASSETS / "brand" / "tinyassets-app.ico",
        ASSETS / "brand" / "tinyassets-app.icns",
        TRAY_ICO,
        REPO / "mobile" / "resources" / "icon.png",
        REPO / "mobile" / "resources" / "splash.png",
        REPO / "docs" / "ops" / "play-assets" / "icon-512.png",
        REPO / "docs" / "ops" / "play-assets" / "feature-graphic-1024x500.png",
    ]
    android = sorted((REPO / "mobile" / "resources" / "android").rglob("*.png"))
    return fixed + android


def _sha256(path: Path) -> str:
    if not path.is_file():
        raise SystemExit(f"render_marks: expected generated file is missing: {path}")
    data = path.read_bytes()
    if path.suffix.lower() in {".html", ".py", ".svg", ".tsx", ".webmanifest"}:
        data = data.replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def _write_provenance(mark_version: str) -> None:
    """Bind every committed export to the canonical drawing and its generators."""
    generators = [
        REPO / "tinyassets" / "desktop" / "icon_gen.py",
        Path(__file__).resolve(),
        REPO / "mobile" / "scripts" / "render_app_icons.py",
    ]
    manifest = {
        "schema_version": 1,
        "canonical_source": "tinyassets/desktop/icon_gen.py",
        "mark_version": mark_version,
        "generators": {
            path.relative_to(REPO).as_posix(): _sha256(path)
            for path in generators
        },
        "generated": {
            path.relative_to(REPO).as_posix(): _sha256(path)
            for path in _generated_paths()
        },
    }
    _write(PROVENANCE, json.dumps(manifest, indent=2, sort_keys=True) + "\n")


def main() -> int:
    bare_svg = mark_svg(tile=False, detail="full")
    compact_svg = mark_svg(tile=False, detail="compact")
    tile_svg = mark_svg(tile=True, detail="compact")
    micro_svg = mark_svg(tile=True, detail="micro")
    mark_version = hashlib.sha256(
        "\n".join((bare_svg, compact_svg, tile_svg, micro_svg)).encode("utf-8")
    ).hexdigest()[:12]

    # Brand source exports.
    _write(BRAND / "mark.svg", bare_svg)
    _write(BRAND / "mark-compact.svg", compact_svg)
    _write(BRAND / "mark-tile.svg", tile_svg)

    # The site's inline React mark, generated from the same geometry so a
    # change to icon_gen.py cannot leave the web mark behind.
    _write_component(mark_version)

    # Site.
    _ico(SITE_PUBLIC / "favicon.ico", (16, 32, 48))
    _write(SITE_PUBLIC / "icon.svg", tile_svg)
    _png(SITE_PUBLIC / "apple-touch-icon.png", 180, tile=True)
    _png(SITE_PUBLIC / "icon-192.png", 192, tile=True)
    _png(SITE_PUBLIC / "icon-512.png", 512, tile=True)
    _png(SITE_PUBLIC / "logo-mark.png", 512, tile=True)
    _png(SITE_PUBLIC / "tinyassets-mark.png", 512, tile=False, detail="full")
    _write_site_manifest(mark_version)

    # Repo brand assets.
    _png(ASSETS / "icon.png", 512, tile=True)
    _write(ASSETS / "icon.svg", tile_svg)
    _png(ASSETS / "brand" / "tinyassets-logo-icon.png", 512, tile=True)
    _write(ASSETS / "brand" / "tinyassets-logo-icon.svg", tile_svg)
    _png(ASSETS / "brand" / "tinyassets-logo-mark.png", 512, tile=False,
         detail="full")
    _write(ASSETS / "brand" / "tinyassets-logo-mark.svg", bare_svg)
    _ico(ASSETS / "brand" / "tinyassets-app.ico", (16, 32, 48, 64, 128, 256))
    _icns(ASSETS / "brand" / "tinyassets-app.icns")

    # The served web app.
    _write_app_html(tile_svg)

    # Tray.
    generate_icon(TRAY_ICO)
    print(TRAY_ICO.relative_to(REPO).as_posix())

    # Android + Play listing, through the mobile renderer's own contract.
    logo = ASSETS / "icon.png"
    subprocess.run(
        [sys.executable, "scripts/render_app_icons.py", "--from-logo", str(logo)],
        cwd=REPO / "mobile",
        check=True,
    )
    _write_provenance(mark_version)
    return 0


if __name__ == "__main__":
    sys.exit(main())
